theme = "catppuccin_macchiato"

[editor]
cursorline = true
color-modes = true
line-number = "relative"
rulers = [80]
bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true

