color:
    when: auto
size: short
total-size: false
indicators: false
no-symlink: false
icons:
    when: auto
    theme: fancy
date: '+%Y-%m-%d %H:%M'
blocks:
    - permission
    - size
    - date
    - git
    - name
symlink-arrow: ->
